# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "ahci" "xhci_pci" "virtio_pci" "sr_mod" "virtio_blk" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/ccf684f2-b933-4875-80ba-cbe480c4c5ed";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/ccf684f2-b933-4875-80ba-cbe480c4c5ed";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/ccf684f2-b933-4875-80ba-cbe480c4c5ed";
      fsType = "btrfs";
      options = [ "subvol=@nix" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/ccf684f2-b933-4875-80ba-cbe480c4c5ed";
      fsType = "btrfs";
      options = [ "subvol=@log" ];
    };

  fileSystems."/var/cache" =
    { device = "/dev/disk/by-uuid/ccf684f2-b933-4875-80ba-cbe480c4c5ed";
      fsType = "btrfs";
      options = [ "subvol=@cache" ];
    };

  fileSystems."/persist" =
    { device = "/dev/disk/by-uuid/ccf684f2-b933-4875-80ba-cbe480c4c5ed";
      fsType = "btrfs";
      options = [ "subvol=@persist" ];
    };

  fileSystems."/.snapshots" =
    { device = "/dev/disk/by-uuid/ccf684f2-b933-4875-80ba-cbe480c4c5ed";
      fsType = "btrfs";
      options = [ "subvol=@snapshots" ];
    };

  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/3591-5108";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/62ff3288-267a-47f0-9d10-988c1d654c60"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
